"""Credential pattern library. Rust-regex compatible (rg): no lookaround or backreferences.

Tier A = vendor-specific prefix or format; B = structural; C = contextual and weak (noisy by design).
Each pattern runs as its OWN rg pass so rg's literal-prefix fast path applies.
"""
import re

PATTERNS = [
# ---- AI / LLM providers ----
("anthropic_key",            r"\bsk-ant-(?:api|admin|oat|ort)[0-9]{2}-[A-Za-z0-9_\-]{80,}", "A"),
("openai_project_key",       r"\bsk-(?:proj|svcacct|admin)-[A-Za-z0-9_\-]{40,}", "A"),
("openai_legacy_key",        r"\bsk-[A-Za-z0-9]{20}T3BlbkFJ[A-Za-z0-9]{20}\b", "A"),
("google_api_key",           r"\bAIza[0-9A-Za-z_\-]{35}\b", "A"),
("groq_key",                 r"\bgsk_[A-Za-z0-9]{50,}\b", "A"),
("openrouter_key",           r"\bsk-or-v1-[a-f0-9]{64}\b", "A"),
("huggingface_token",        r"\bhf_[A-Za-z0-9]{30,40}\b", "A"),
("replicate_token",          r"\br8_[A-Za-z0-9]{37}\b", "A"),
("perplexity_key",           r"\bpplx-[A-Za-z0-9]{40,56}\b", "A"),
("elevenlabs_key",           r"\bsk_[a-f0-9]{48}\b", "A"),
("xai_key",                  r"xai-[A-Za-z0-9]{70,120}", "A"),   # no \b: keys appear glued to text
("deepgram_ctx",             r"(?i)deepgram[a-z_]*[\"']?\s*[:=]\s*[\"']?[a-f0-9]{40}\b", "A"),
("assemblyai_ctx",           r"(?i)assembly[a-z_]*key[\"']?\s*[:=]\s*[\"']?[a-f0-9]{32}\b", "A"),
# ---- Cloud ----
("aws_access_key_id",        r"\b(?:AKIA|ASIA|ABIA|ACCA)[0-9A-Z]{16}\b", "A"),
("aws_secret_key_ctx",       r"(?i)aws_?secret_?access_?key[\"']?\s*[:=]\s*[\"']?[A-Za-z0-9/+=]{40}\b", "A"),
("aws_session_token_ctx",    r"(?i)aws_?session_?token[\"']?\s*[:=]\s*[\"']?[A-Za-z0-9/+=]{100,}", "A"),
("azure_storage_key",        r"AccountKey=[A-Za-z0-9+/]{80,}={0,2}", "A"),
("azure_conn_string",        r"DefaultEndpointsProtocol=https?;AccountName=[A-Za-z0-9]+", "B"),
("azure_sas_signature",      r"[?&]sig=[A-Za-z0-9%+/=]{40,}", "B"),
("azure_ad_client_secret",   r"(?i)(?:client_?secret|azure_client_secret)[\"']?\s*[:=]\s*[\"']?[A-Za-z0-9~._\-]{34,40}\b", "A"),
("azure_openai_key_ctx",     r"(?i)(?:azure_openai_(?:api_)?key|foundry_(?:api_)?key|cognitive[a-z_]*key)[\"']?\s*[:=]\s*[\"']?[A-Za-z0-9]{32,84}\b", "A"),
("gcp_client_secret",        r"\bGOCSPX-[A-Za-z0-9_\-]{28}\b", "A"),
("gcp_oauth_access_token",   r"\bya29\.[0-9A-Za-z_\-]{50,}", "A"),
("gcp_oauth_refresh_token",  r"\b1//0[0-9A-Za-z_\-]{50,}", "A"),
("google_oauth_auth_code",   r"\b4(?:/|%2F)0A[A-Za-z0-9_\-]{40,}", "B"),
("gcp_sa_private_key_id",    r"\"private_key_id\"\s*:\s*\"[a-f0-9]{40}\"", "A"),
("gcp_service_account_json", r"\"type\"\s*:\s*\"service_account\"", "B"),
("google_session_cookie_ctx",r"\b(?:__Secure-[13]PSID[A-Z]*|SAPISID|APISID|HSID|SSID|SID)[\"']?\s*[:=,]\s*[\"']?(?:value[\"']?\s*:\s*[\"']?)?[A-Za-z0-9_\-./]{40,}", "A"),
("digitalocean_token",       r"\bdo[opr]_v1_[a-f0-9]{64}\b", "A"),
("cloudflare_token_ctx",     r"(?i)cloudflare[a-z_]*(?:token|key)[\"']?\s*[:=]\s*[\"']?[A-Za-z0-9_\-]{37,40}\b", "A"),
("vercel_token_ctx",         r"(?i)vercel[a-z_]*token[\"']?\s*[:=]\s*[\"']?[A-Za-z0-9]{24}\b", "A"),
("netlify_token_ctx",        r"(?i)netlify[a-z_]*token[\"']?\s*[:=]\s*[\"']?[A-Za-z0-9_\-]{40,}", "A"),
("flyio_token",              r"\bfo1_[A-Za-z0-9_\-]{40,}", "A"),
("terraform_cloud_token",    r"\b[A-Za-z0-9]{14}\.atlasv1\.[A-Za-z0-9_\-]{60,}", "A"),
("heroku_key_ctx",           r"(?i)heroku[a-z_]*key[\"']?\s*[:=]\s*[\"']?[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}\b", "A"),
("railway_token_ctx",        r"(?i)railway[a-z_]*token[\"']?\s*[:=]\s*[\"']?[0-9a-f\-]{36}\b", "A"),
("supabase_service_key_ctx", r"(?i)(?:supabase_service_role_key|service_role)[\"']?\s*[:=]\s*[\"']?eyJ[A-Za-z0-9_\-.]{50,}", "A"),
("supabase_secret_key",      r"\bsb_secret_[A-Za-z0-9_\-]{20,}", "A"),
# ---- VCS / package registries ----
("github_token",             r"\bgh[pousr]_[A-Za-z0-9]{36,255}\b", "A"),
("github_fine_grained_pat",  r"\bgithub_pat_[A-Za-z0-9_]{80,}\b", "A"),
("gitlab_token",             r"\bgl(?:pat|dt|rt|ptt|cbt|oas)-[A-Za-z0-9_\-]{20,}", "A"),
("bitbucket_ctx",            r"(?i)bitbucket[a-z_]*(?:password|token)[\"']?\s*[:=]\s*[\"']?[A-Za-z0-9_\-]{20,}", "A"),
("npm_token",                r"\bnpm_[A-Za-z0-9]{36}\b", "A"),
("npmrc_auth_token",         r"_authToken\s*=\s*[A-Za-z0-9_\-.]{20,}", "A"),
("pypi_token",               r"\bpypi-AgEIcHlwaS5vcmc[A-Za-z0-9_\-]{50,}", "A"),
("rubygems_key",             r"\brubygems_[a-f0-9]{48}\b", "A"),
("dockerhub_pat",            r"\bdckr_pat_[A-Za-z0-9_\-]{27,}", "A"),
("jfrog_access_token",       r"\bAKCp[A-Za-z0-9]{69,}\b", "A"),
("jfrog_reference_token",    r"\bcmVmdG9rZW46[A-Za-z0-9+/=]{20,}", "A"),
("jfrog_ctx",                r"(?i)(?:artifactory|jfrog)[a-z_]*(?:api_?key|token|password)[\"']?\s*[:=]\s*[\"']?[A-Za-z0-9_\-.]{40,}", "A"),
# ---- Comms / SaaS ----
("slack_token",              r"\bxox[abposre]-[A-Za-z0-9\-]{10,}", "A"),
("slack_webhook",            r"https://hooks\.slack\.com/services/T[A-Za-z0-9_]{6,}/B[A-Za-z0-9_]{6,}/[A-Za-z0-9_]{20,}", "A"),
("discord_bot_token",        r"\b[MNO][A-Za-z0-9_\-]{23,26}\.[A-Za-z0-9_\-]{6}\.[A-Za-z0-9_\-]{27,38}\b", "A"),
("discord_webhook",          r"https://(?:ptb\.|canary\.)?discord(?:app)?\.com/api/webhooks/[0-9]{17,20}/[A-Za-z0-9_\-]{60,}", "A"),
("telegram_bot_token",       r"\b[0-9]{8,10}:AA[A-Za-z0-9_\-]{33}\b", "A"),
("twilio_ctx",               r"(?i)twilio[a-z_]*(?:auth_?token|api_?secret)[\"']?\s*[:=]\s*[\"']?[a-f0-9]{32}\b", "A"),
("twilio_api_key_sid",       r"\bSK[a-f0-9]{32}\b", "B"),
("sendgrid_key",             r"\bSG\.[A-Za-z0-9_\-]{22}\.[A-Za-z0-9_\-]{43}\b", "A"),
("mailgun_key",              r"\bkey-[a-f0-9]{32}\b", "A"),
("mailchimp_key",            r"\b[a-f0-9]{32}-us[0-9]{1,2}\b", "A"),
("resend_key",               r"\bre_[A-Za-z0-9]{8}_[A-Za-z0-9]{24}\b", "A"),
("postmark_ctx",             r"(?i)postmark[a-z_]*token[\"']?\s*[:=]\s*[\"']?[0-9a-f\-]{36}\b", "A"),
("stripe_secret_key",        r"\b[sr]k_(?:live|test)_[0-9A-Za-z]{20,}\b", "A"),
("stripe_webhook_secret",    r"\bwhsec_[A-Za-z0-9]{32,}\b", "A"),
("square_token",             r"\b(?:sq0atp|sq0csp)-[A-Za-z0-9_\-]{22,}\b|\bEAAA[A-Za-z0-9_\-]{60}\b", "A"),
("shopify_token",            r"\bshp(?:at|ca|pa|ss)_[a-fA-F0-9]{32}\b", "A"),
("airtable_key",             r"\bkey[A-Za-z0-9]{14}\b|\bpat[A-Za-z0-9]{14}\.[a-f0-9]{64}\b", "A"),
("asana_pat",                r"\b[12]/[0-9]{16}(?:/[0-9]{16})?:[a-f0-9]{32}\b", "A"),
("atlassian_api_token",      r"\bATATT3[A-Za-z0-9_\-=]{100,}", "A"),
("atlassian_ctx",            r"(?i)(?:jira|confluence|atlassian)[a-z_]*(?:token|password)[\"']?\s*[:=]\s*[\"']?[A-Za-z0-9_\-=]{20,}", "A"),
("notion_token",             r"\b(?:secret_[A-Za-z0-9]{43}|ntn_[A-Za-z0-9]{40,})\b", "A"),
("linear_key",               r"\blin_api_[A-Za-z0-9]{40}\b", "A"),
("figma_token",              r"\bfigd_[A-Za-z0-9_\-]{40,}", "A"),
("sentry_dsn",               r"https://[a-f0-9]{32}@[a-z0-9.\-]*sentry\.io/[0-9]+", "A"),
("sentry_token",             r"\bsntry[su]_[A-Za-z0-9+/=_]{40,}", "A"),
("datadog_ctx",              r"(?i)(?:dd_api_key|dd_app_key|datadog[a-z_]*key)[\"']?\s*[:=]\s*[\"']?[a-f0-9]{32,40}\b", "A"),
("newrelic_key",             r"\bNRAK-[A-Z0-9]{27}\b", "A"),
("posthog_key",              r"\bph[cx]_[A-Za-z0-9]{43}\b", "B"),
("algolia_ctx",              r"(?i)algolia[a-z_]*(?:admin|api)_?key[\"']?\s*[:=]\s*[\"']?[a-f0-9]{32}\b", "A"),
("brave_api_key_ctx",        r"(?i)brave[a-z_]*key[\"']?\s*[:=]\s*[\"']?BSA[A-Za-z0-9_\-]{25,32}\b", "A"),
("brave_api_key",            r"\bBSA[A-Za-z0-9_\-]{25,32}\b", "A"),
("mapbox_secret_token",      r"\bsk\.eyJ[A-Za-z0-9_\-.]{50,}", "A"),
("salesforce_session",       r"\b00D[A-Za-z0-9]{12,15}![A-Za-z0-9._]{80,}", "A"),
("salesforce_ctx",           r"(?i)\b(?:sf|sfdc|salesforce)_[a-z_]*(?:token|secret|password)[\"']?\s*[:=]\s*[\"']?[^\s\"']{12,}", "A"),
("linkedin_li_at_ctx",       r"(?i)\bli_at[\"']?\s*[:=,]\s*[\"']?(?:value[\"']?\s*:\s*[\"']?)?AQED[A-Za-z0-9_\-]{100,}", "A"),
("linkedin_cookie_bare",     r"\bAQED[A-Za-z0-9_\-]{100,}", "A"),
("session_cookie_ctx",       r"(?i)\b(?:sessionid|session_id|connect\.sid|_session|auth_token|access_token)[\"']?\s*[:=]\s*[\"']?[A-Za-z0-9_\-.%]{40,}", "B"),
# ---- Keys / structural ----
("private_key_pem_body",     r"-----BEGIN (?:RSA |EC |DSA |OPENSSH |ENCRYPTED )?PRIVATE KEY-----(?:\\\\n|\\n|\s){1,4}[A-Za-z0-9+/]{60,}", "A"),
("private_key_header",       r"-----BEGIN (?:RSA |EC |DSA |OPENSSH |PGP |ENCRYPTED )?PRIVATE KEY", "B"),
("pgp_private_block",        r"-----BEGIN PGP PRIVATE KEY BLOCK-----", "A"),
("putty_private_key",        r"PuTTY-User-Key-File-[23]:\s*[a-z0-9\-]+", "B"),
("age_secret_key",           r"\bAGE-SECRET-KEY-1[0-9A-Z]{58}\b", "A"),
("jwt",                      r"\beyJ[A-Za-z0-9_\-]{10,}\.eyJ[A-Za-z0-9_\-]{10,}\.[A-Za-z0-9_\-]{10,}", "B"),
("basic_auth_header",        r"(?i)authorization[\"']?\s*[:=]\s*[\"']?basic\s+[A-Za-z0-9+/=]{16,}", "B"),
("bearer_header",            r"(?i)authorization[\"']?\s*[:=]\s*[\"']?bearer\s+[A-Za-z0-9_\-.=+/]{24,}", "B"),
("curl_user_flag",           r"(?:-u|--user)\s+[\"']?[^\s:\"']{2,}:[^\s\"']{6,}", "B"),
("url_with_credentials",     r"\b(?:https?|postgres(?:ql)?|mysql|mariadb|mongodb(?:\+srv)?|redis|rediss|amqps?|ftp|sftp|smtps?|imaps?|ldaps?)://[^:@/\s\"'<>]{1,64}:[^@/\s\"'<>]{3,128}@", "B"),
("prefixed_key",             r"\b(?:sk|pk|rk|ak|api|key|tok|token|secret)[0-9]?_[A-Za-z0-9]{24,}\b", "B"),
("htpasswd_hash",            r"\$(?:2[aby]|apr1|6|5)\$[A-Za-z0-9./$]{20,}", "B"),
# ---- Microsoft / Azure formats ----
("entra_client_secret",      r"\b[A-Za-z0-9_~.]{3}[0-9]Q~[A-Za-z0-9_~.\-]{31,34}", "A"),
("azure_devops_pat",         r"\b[A-Za-z0-9]{76}AZDO[A-Za-z0-9]{4}\b", "A"),
("azure_devops_pat_ctx",     r"(?i)(?:azure[_-]?devops|azdo|ado|devops)[a-z_]*(?:pat|token)[\"']?\s*[:=]\s*[\"']?[a-z2-7]{52}\b", "A"),
("azure_identifiable_key",   r"\b[A-Za-z0-9]{52}JQQJ9[A-Za-z0-9]{27}\b", "A"),
("azure_identifiable_b64_44", r"[A-Za-z0-9+/]{33}(?:\+AS[bt]|\+AEh|\+ARm|AzCa|AzFu|ACDb|APIM|AzSe)[A-Za-z0-9+/]{5}=", "A"),
("azure_identifiable_b64_88", r"[A-Za-z0-9+/]{76}(?:\+AS[bt]|\+AEh|\+ARm|AzCa|AzFu|ACDb|APIM|AzSe)[A-Za-z0-9+/]{5}[AQgw]==", "A"),
("azure_shared_access_key",  r"(?i)\bSharedAccessKey=[A-Za-z0-9+/]{40,}={0,2}", "A"),
("azure_conn_access_key",    r"(?i)(?:^|;)\s*AccessKey=[A-Za-z0-9+/]{40,}={0,2}", "A"),
("azure_function_key_url",   r"https://[a-z0-9\-]+\.azurewebsites\.net/api/[^\s\"'?]*\?(?:[^\s\"']*&)?code=[A-Za-z0-9_\-]{30,}={0,2}", "A"),
("conn_string_password",     r"(?i)(?:^|[;\"'\s])(?:Password|Pwd)\s*=\s*[^;\"'\s]{6,}(?:;|$)", "B"),
# ---- Meta / WhatsApp / Google / registrars / payment + messaging ----
("meta_access_token",        r"\bEAA[A-Za-z0-9]{90,}", "A"),
("fcm_server_key",           r"\bAAAA[A-Za-z0-9_\-]{7}:APA91b[A-Za-z0-9_\-]{120,}", "A"),
("google_client_secret_json",r"\"client_secret\"\s*:\s*\"[A-Za-z0-9_\-]{24,40}\"", "A"),
("google_chat_webhook",      r"https://chat\.googleapis\.com/v1/spaces/[A-Za-z0-9_\-]+/messages\?key=[A-Za-z0-9_\-]{30,}&token=[A-Za-z0-9_\-%]{30,}", "A"),
("porkbun_api_key",          r"\b(?:pk1|sk1)_[a-f0-9]{64}\b", "A"),
("registrar_dns_ctx",        r"(?i)(?:godaddy|namecheap|cloudns|porkbun|gandi|dnsimple|route53|isoc|domain[_-]?the[_-]?net)[a-z_]*(?:key|secret|token|password)[\"']?\s*[:=]\s*[\"']?[A-Za-z0-9_\-]{16,}", "A"),
("whatsapp_gateway_ctx",     r"(?i)(?:green[-_]?api|ultramsg|wati|whatsapp|waba|360dialog|maytapi|wassenger)[a-z_]*(?:token|key|secret)[\"']?\s*[:=]\s*[\"']?[A-Za-z0-9_\-]{20,}", "A"),
("il_payment_ctx",           r"(?i)(?:tranzila|cardcom|meshulam|payplus|pelecard|icount|greeninvoice|green[_-]?invoice|isracard|yaad|grow[_-]?payment)[a-z_]*(?:key|secret|token|password|pass)[\"']?\s*[:=]\s*[\"']?[^\s\"']{8,}", "A"),
("teams_webhook",            r"https://[a-z0-9\-]+\.webhook\.office\.com/webhookb2/[A-Za-z0-9@\-]{30,}/IncomingWebhook/[A-Za-z0-9]{32}/[A-Za-z0-9\-]{36}", "A"),
("zapier_webhook",           r"https://hooks\.zapier\.com/hooks/catch/[0-9]+/[A-Za-z0-9]+", "B"),
("make_webhook",             r"https://hook\.(?:[a-z0-9]+\.)?make\.com/[a-z0-9]{32}", "B"),
# ---- private keys without PEM headers (base64 DER bodies) ----
("pkcs8_rsa_key_body",       r"\bMII[A-Za-z0-9+/]{3}IBADANBgkqhkiG9w0BAQEFAASC", "A"),
("pkcs1_rsa_key_body",       r"\bMII[A-Za-z0-9+/]{3}IBAAKC[AgQ]", "A"),
("pkcs8_ec_key_body",        r"\bMIG[A-Za-z0-9+/]AgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG", "A"),
("pkcs8_ed25519_key_body",   r"\bMC4CAQAwBQYDK2VwBCIEI[A-Za-z0-9+/]{40,}", "A"),
("openssh_key_body",         r"\bb3BlbnNzaC1rZXktdjE[A-Za-z0-9+/]{60,}", "A"),
("private_key_pem_multiline",r"-----BEGIN (?:RSA |EC |DSA |OPENSSH |ENCRYPTED )?PRIVATE KEY-----\r?\n[A-Za-z0-9+/=]{40,}", "A"),
# ---- structural: headers, cookies, CLI flags, URL params, prose ----
("http_header_key",          r"(?i)\b(?:x-api-key|api-key|x-auth-token|x-access-token|x-goog-api-key|xi-api-key|ocp-apim-subscription-key|x-functions-key|subscription-key|private-token|x-api-token|x-app-token|x-client-secret|apikey)[\"']?\s*[:=]\s*[\"']?[A-Za-z0-9_\-+/=.~]{16,}", "B"),
("bearer_literal",           r"(?i)[\"'`]Bearer\s+[A-Za-z0-9_\-.=+/]{24,}[\"'`]", "B"),
("cookie_header",            r"(?i)\b(?:cookie|set-cookie)[\"']?\s*[:=]\s*[\"']?(?:[^\"'\r\n;]{1,100};\s*){0,12}[A-Za-z0-9_.\-]{2,40}=[A-Za-z0-9%_\-+/.=:]{32,}", "B"),
("curl_cookie_flag",         r"(?:\s-b|--cookie)\s+[\"'][^\"']{0,200}=[A-Za-z0-9%_\-+/.=]{32,}", "B"),
("cli_secret_flag",          r"--(?:password|passwd|pass|token|api-key|apikey|secret|client-secret|access-key|secret-key|auth-token)(?:=|\s+)[\"']?[^\s\"'$<{\-][^\s\"']{5,}", "B"),
("sshpass_mysql_flag",       r"\bsshpass\s+-p\s*[\"']?[^\s\"']{4,}|\bmysql(?:dump|admin)?\s[^\n|;]{0,80}\s-p[^\s\"'\-][^\s\"']{3,}", "B"),
("url_secret_param",         r"[?&](?:access_token|api_key|apikey|api-key|token|auth_token|secret|client_secret|password|passwd|pwd|key|code|signature|x-amz-signature|x-goog-signature)=[A-Za-z0-9_\-%.~+/=]{20,}", "B"),
("requests_basic_auth",      r"(?i)\bauth\s*=\s*\(\s*[\"'][^\"']{2,}[\"']\s*,\s*[\"'][^\"']{6,}[\"']\s*\)", "B"),
("user_password_pair",       r"(?i)\b(?:user(?:name)?|login|email)\s*[:=]\s*\S{3,}\s*[,;/|]?\s*(?:pass(?:word)?|pwd)\s*[:=]\s*[^\s\"']{6,}", "B"),
("hebrew_password_prose",    r"(?:סיסמ[הא]|סיסמת\S*|קוד\s+(?:גישה|כניסה|אימות)|טוקן|מפתח\s+(?:API|api|גישה|סודי))\s*(?:היא|הוא|זה|:|=|-|–)?\s*[`\"'׳״]?[^\s`\"'׳״]{6,}", "C"),
("apps_script_deployment_id",r"\bAKfycb[A-Za-z0-9_\-]{40,}", "C"),
("env_assignment",           r"(?i)\b[A-Z0-9_]*(?:SECRET|TOKEN|PASSWORD|PASSWD|PASSPHRASE|APIKEY|API_KEY|PRIVATE_KEY|CREDENTIAL|ACCESS_KEY|AUTH_KEY|CLIENT_SECRET)[A-Z0-9_]*[\"']?\s*[:=]\s*[\"']?[^\s\"'&;,}{)(\]\[<>]{8,}", "C"),
("generic_hex_secret",       r"(?i)(?:secret|token|api_?key|password|signing_?key)[\"']?\s*[:=]\s*[\"']?[a-f0-9]{32,128}\b", "C"),
("password_in_prose",        r"(?i)\bpassword\s*(?:is|:)\s*[`\"']?[^\s`\"']{8,}", "C"),
]

# patterns that must run in rg multiline mode (-U)
MULTILINE = {"private_key_pem_multiline"}


def escape_aware(rx):
    """A token right after a JSON escape (literal backslash-n) has no \\b boundary because 'n' is a word
    character. Let every leading \\b also accept an escape; the residue is stripped per match."""
    return re.sub(r"(^(?:\(\?i\))?|\|)\\b",
                  lambda m: m.group(1) + r"(?:\b|\\[ntr]|\\u00[0-9a-fA-F]{2}|%[0-9A-Fa-f]{2})", rx)


RESIDUE = re.compile(rb"^(?:\\[ntr]|\\u00[0-9a-fA-F]{2}|%[0-9A-Fa-f]{2})")


def strip_residue(m, off):
    r = RESIDUE.match(m)
    return (m[r.end():], off + r.end()) if r else (m, off)


TIERS = {name: tier for name, _, tier in PATTERNS}

LABELS = {
    "anthropic_key": "Anthropic API key",
    "openai_project_key": "OpenAI API key",
    "openai_legacy_key": "OpenAI API key (legacy format)",
    "google_api_key": "Google API key",
    "groq_key": "Groq API key",
    "openrouter_key": "OpenRouter API key",
    "huggingface_token": "Hugging Face token",
    "replicate_token": "Replicate API token",
    "perplexity_key": "Perplexity API key",
    "elevenlabs_key": "ElevenLabs API key",
    "xai_key": "xAI (Grok) API key",
    "deepgram_ctx": "Deepgram API key",
    "assemblyai_ctx": "AssemblyAI API key",
    "aws_access_key_id": "AWS access key ID",
    "aws_secret_key_ctx": "AWS secret access key",
    "aws_session_token_ctx": "AWS session token",
    "azure_storage_key": "Azure Storage account key",
    "azure_conn_string": "Azure Storage connection string",
    "azure_sas_signature": "Azure SAS signature",
    "azure_ad_client_secret": "Azure AD client secret",
    "azure_openai_key_ctx": "Azure OpenAI / AI Foundry key",
    "gcp_client_secret": "Google OAuth client secret",
    "gcp_oauth_access_token": "Google OAuth access token",
    "gcp_oauth_refresh_token": "Google OAuth refresh token",
    "google_oauth_auth_code": "Google OAuth authorization code",
    "gcp_sa_private_key_id": "Google service account key",
    "gcp_service_account_json": "Google service account JSON",
    "google_session_cookie_ctx": "Google session cookie",
    "digitalocean_token": "DigitalOcean token",
    "cloudflare_token_ctx": "Cloudflare API token",
    "vercel_token_ctx": "Vercel token",
    "netlify_token_ctx": "Netlify token",
    "flyio_token": "Fly.io token",
    "terraform_cloud_token": "Terraform Cloud token",
    "heroku_key_ctx": "Heroku API key",
    "railway_token_ctx": "Railway token",
    "supabase_service_key_ctx": "Supabase service role key",
    "supabase_secret_key": "Supabase secret key",
    "github_token": "GitHub token",
    "github_fine_grained_pat": "GitHub fine-grained token",
    "gitlab_token": "GitLab token",
    "bitbucket_ctx": "Bitbucket app password or token",
    "npm_token": "npm token",
    "npmrc_auth_token": "npm auth token (.npmrc)",
    "pypi_token": "PyPI API token",
    "rubygems_key": "RubyGems API key",
    "dockerhub_pat": "Docker Hub access token",
    "jfrog_access_token": "JFrog access token",
    "jfrog_reference_token": "JFrog reference token",
    "jfrog_ctx": "JFrog Artifactory credential",
    "slack_token": "Slack token",
    "slack_webhook": "Slack webhook URL",
    "discord_bot_token": "Discord bot token",
    "discord_webhook": "Discord webhook URL",
    "telegram_bot_token": "Telegram bot token",
    "twilio_ctx": "Twilio auth token",
    "twilio_api_key_sid": "Twilio API key SID",
    "sendgrid_key": "SendGrid API key",
    "mailgun_key": "Mailgun API key",
    "mailchimp_key": "Mailchimp API key",
    "resend_key": "Resend API key",
    "postmark_ctx": "Postmark server token",
    "stripe_secret_key": "Stripe secret key",
    "stripe_webhook_secret": "Stripe webhook secret",
    "square_token": "Square access token",
    "shopify_token": "Shopify access token",
    "airtable_key": "Airtable API key",
    "asana_pat": "Asana personal access token",
    "atlassian_api_token": "Atlassian API token",
    "atlassian_ctx": "Atlassian (Jira/Confluence) credential",
    "notion_token": "Notion integration token",
    "linear_key": "Linear API key",
    "figma_token": "Figma access token",
    "sentry_dsn": "Sentry DSN",
    "sentry_token": "Sentry auth token",
    "datadog_ctx": "Datadog API key",
    "newrelic_key": "New Relic API key",
    "posthog_key": "PostHog key",
    "algolia_ctx": "Algolia API key",
    "brave_api_key_ctx": "Brave Search API key",
    "brave_api_key": "Brave Search API key",
    "mapbox_secret_token": "Mapbox secret token",
    "salesforce_session": "Salesforce session ID",
    "salesforce_ctx": "Salesforce credential",
    "linkedin_li_at_ctx": "LinkedIn session cookie",
    "linkedin_cookie_bare": "LinkedIn session cookie",
    "session_cookie_ctx": "Session cookie or token",
    "private_key_pem_body": "Private key",
    "private_key_header": "Private key",
    "pgp_private_block": "PGP private key",
    "putty_private_key": "PuTTY private key",
    "age_secret_key": "age secret key",
    "jwt": "JSON Web Token",
    "basic_auth_header": "HTTP Basic credentials",
    "bearer_header": "Bearer token",
    "curl_user_flag": "curl username and password",
    "url_with_credentials": "URL with embedded password",
    "prefixed_key": "Prefixed API key",
    "htpasswd_hash": "Password hash",
    "entra_client_secret": "Microsoft Entra client secret",
    "azure_devops_pat": "Azure DevOps personal access token",
    "azure_devops_pat_ctx": "Azure DevOps personal access token",
    "azure_identifiable_key": "Azure API key",
    "azure_identifiable_b64_44": "Azure access key",
    "azure_identifiable_b64_88": "Azure access key",
    "azure_shared_access_key": "Azure shared access key",
    "azure_conn_access_key": "Azure connection string access key",
    "azure_function_key_url": "Azure Function key in URL",
    "conn_string_password": "Connection string password",
    "meta_access_token": "Meta (Facebook/WhatsApp) access token",
    "fcm_server_key": "Firebase Cloud Messaging server key",
    "google_client_secret_json": "Google OAuth client secret",
    "google_chat_webhook": "Google Chat webhook URL",
    "porkbun_api_key": "Porkbun API key",
    "registrar_dns_ctx": "Domain registrar / DNS API key",
    "whatsapp_gateway_ctx": "WhatsApp gateway token",
    "il_payment_ctx": "Payment provider credential",
    "teams_webhook": "Microsoft Teams webhook URL",
    "zapier_webhook": "Zapier webhook URL",
    "make_webhook": "Make webhook URL",
    "pkcs8_rsa_key_body": "RSA private key",
    "pkcs1_rsa_key_body": "RSA private key",
    "pkcs8_ec_key_body": "EC private key",
    "pkcs8_ed25519_key_body": "Ed25519 private key",
    "openssh_key_body": "OpenSSH private key",
    "private_key_pem_multiline": "Private key",
    "http_header_key": "API key in HTTP header",
    "bearer_literal": "Bearer token",
    "cookie_header": "Cookie header",
    "curl_cookie_flag": "Cookie passed to curl",
    "cli_secret_flag": "Secret passed as a command-line flag",
    "sshpass_mysql_flag": "Password passed to sshpass or mysql",
    "url_secret_param": "Secret in URL parameter",
    "requests_basic_auth": "Username and password in code",
    "user_password_pair": "Username and password",
    "hebrew_password_prose": "Password written in a prompt (Hebrew)",
    "apps_script_deployment_id": "Apps Script deployment ID",
    "env_assignment": "Secret-named variable assignment",
    "generic_hex_secret": "Hex secret",
    "password_in_prose": "Password written in text",
}

_GOOGLE = ("Google Cloud credentials", "https://console.cloud.google.com/apis/credentials")
_AWS = ("AWS IAM security credentials", "https://console.aws.amazon.com/iam/home#/security_credentials")
_AZURE = ("Azure portal", "https://portal.azure.com")
REVOKE = {
    "anthropic_key": ("Anthropic Console", "https://console.anthropic.com/settings/keys"),
    "openai_project_key": ("OpenAI Platform", "https://platform.openai.com/api-keys"),
    "openai_legacy_key": ("OpenAI Platform", "https://platform.openai.com/api-keys"),
    "google_api_key": _GOOGLE, "gcp_client_secret": _GOOGLE, "google_client_secret_json": _GOOGLE,
    "gcp_oauth_access_token": _GOOGLE, "gcp_oauth_refresh_token": _GOOGLE,
    "aws_access_key_id": _AWS, "aws_secret_key_ctx": _AWS, "aws_session_token_ctx": _AWS,
    "azure_storage_key": _AZURE, "azure_conn_string": _AZURE, "azure_sas_signature": _AZURE,
    "azure_ad_client_secret": _AZURE, "azure_openai_key_ctx": _AZURE, "azure_devops_pat": _AZURE,
    "azure_devops_pat_ctx": _AZURE, "azure_identifiable_key": _AZURE, "azure_identifiable_b64_44": _AZURE,
    "azure_identifiable_b64_88": _AZURE, "azure_shared_access_key": _AZURE, "azure_conn_access_key": _AZURE,
    "azure_function_key_url": _AZURE, "entra_client_secret": _AZURE,
    "github_token": ("GitHub tokens", "https://github.com/settings/tokens"),
    "github_fine_grained_pat": ("GitHub tokens", "https://github.com/settings/tokens"),
    "gitlab_token": ("GitLab access tokens", "https://gitlab.com/-/user_settings/personal_access_tokens"),
    "atlassian_api_token": ("Atlassian API tokens", "https://id.atlassian.com/manage-profile/security/api-tokens"),
    "atlassian_ctx": ("Atlassian API tokens", "https://id.atlassian.com/manage-profile/security/api-tokens"),
    "huggingface_token": ("Hugging Face tokens", "https://huggingface.co/settings/tokens"),
    "xai_key": ("xAI Console", "https://console.x.ai"),
    "groq_key": ("Groq Console", "https://console.groq.com/keys"),
    "openrouter_key": ("OpenRouter keys", "https://openrouter.ai/settings/keys"),
    "slack_token": ("Slack apps", "https://api.slack.com/apps"),
    "slack_webhook": ("Slack apps", "https://api.slack.com/apps"),
    "stripe_secret_key": ("Stripe API keys", "https://dashboard.stripe.com/apikeys"),
    "stripe_webhook_secret": ("Stripe API keys", "https://dashboard.stripe.com/apikeys"),
    "npm_token": ("npm access tokens", "https://www.npmjs.com/settings/~/tokens"),
    "npmrc_auth_token": ("npm access tokens", "https://www.npmjs.com/settings/~/tokens"),
    "pypi_token": ("PyPI API tokens", "https://pypi.org/manage/account/token/"),
    "dockerhub_pat": ("Docker Hub tokens", "https://app.docker.com/settings/personal-access-tokens"),
    "sendgrid_key": ("SendGrid API keys", "https://app.sendgrid.com/settings/api_keys"),
    "notion_token": ("Notion integrations", "https://www.notion.so/profile/integrations"),
    "linear_key": ("Linear API settings", "https://linear.app/settings/account/security"),
    "brave_api_key": ("Brave Search API", "https://api-dashboard.search.brave.com/app/keys"),
    "brave_api_key_ctx": ("Brave Search API", "https://api-dashboard.search.brave.com/app/keys"),
    "digitalocean_token": ("DigitalOcean API", "https://cloud.digitalocean.com/account/api/tokens"),
    "cloudflare_token_ctx": ("Cloudflare API tokens", "https://dash.cloudflare.com/profile/api-tokens"),
    "vercel_token_ctx": ("Vercel tokens", "https://vercel.com/account/tokens"),
    "telegram_bot_token": ("Telegram @BotFather (/revoke)", "https://t.me/BotFather"),
    "discord_bot_token": ("Discord developer portal", "https://discord.com/developers/applications"),
    "discord_webhook": ("Discord developer portal", "https://discord.com/developers/applications"),
    "porkbun_api_key": ("Porkbun API access", "https://porkbun.com/account/api"),
}

# Tier-B structures that are unambiguous secrets: reported under "Rotate now".
ROTATE_B = {"url_with_credentials", "conn_string_password", "basic_auth_header", "bearer_header", "bearer_literal",
            "curl_user_flag", "requests_basic_auth", "sshpass_mysql_flag", "http_header_key"}

# Patterns that match only a fixed key header or DER prefix, not key material: evidence to review, not rotate.
HEADER_ONLY = {"pgp_private_block", "private_key_header", "putty_private_key", "pkcs8_rsa_key_body",
               "pkcs1_rsa_key_body", "pkcs8_ec_key_body"}

# Session cookies expire and are rotated by signing out, so they go to "Review".
SESSION_COOKIE = {"google_session_cookie_ctx", "linkedin_li_at_ctx", "linkedin_cookie_bare", "salesforce_session",
                  "session_cookie_ctx", "cookie_header", "curl_cookie_flag"}

_TIER_A = None


def label_for_value(value):
    """Label of the first tier-A pattern that matches a plaintext value, or None."""
    global _TIER_A
    if _TIER_A is None:
        _TIER_A = [(n, re.compile(r)) for n, r, t in PATTERNS if t == "A" and n not in MULTILINE]
    s = value.decode("utf-8", "replace") if isinstance(value, bytes) else value
    for name, rx in _TIER_A:
        if rx.search(s):
            return LABELS[name]
    return None
